<?xml version="1.0" encoding="UTF-8"?>
<process name="registerUserPasswordHelp" connection-type="Connection-Required" ldap-connection-type="None">
	<activities>
		<activity synchronous="true" continue-on-failure="false" name="retrieveUser">
			<task synchronous="true" continue-on-failure="false" name="setErrorMsg">
				<rule-filename check-for-false="true">is-oid-valid.xml</rule-filename>
				<task-object-name>com.tsa.puridiom.vendorregistration.authentication.tasks.ErrorMsgSetInvalidOrganizationId</task-object-name>
				<post-action>exitProcess</post-action>
			</task>
			<task synchronous="true" continue-on-failure="false" name="authenticationSetup">
				<!-- set Contact_emailAddr & VendorRegister_emailAddr from userId -->
				<task-object-name>com.tsa.puridiom.vendorregistration.authentication.tasks.AuthenticationSetup</task-object-name>
				<post-action></post-action>
			</task>
			<task synchronous="true" continue-on-failure="false" name="contact">
				<task-object-name>com.tsa.puridiom.contact.tasks.ContactRetrieveByEmailAddr</task-object-name>
				<post-action></post-action>
			</task>
			<task synchronous="true" continue-on-failure="false" name="registerUser">
				<rule-filename check-for-false="true">is-contact-empty.xml</rule-filename>
				<task-object-name>com.tsa.puridiom.vendorregister.tasks.RegisterUserSetValuesFromContact</task-object-name>
				<post-action>exitActivity</post-action>
			</task>
			<task synchronous="true" continue-on-failure="false" name="vendorRegister">
				<task-object-name>com.tsa.puridiom.vendorregister.tasks.VendorRegisterRetrieveByContactEmailAddr</task-object-name>
				<post-action></post-action>
			</task>
			<task synchronous="true" continue-on-failure="false" name="registerUser">
				<rule-filename check-for-false="true">is-vendorregister-empty.xml</rule-filename>
				<task-object-name>com.tsa.puridiom.vendorregistration.tasks.RegisterUserSetValuesFromVendorRegister</task-object-name>
				<post-action>exitActivity</post-action>
			</task>
			<!-- Login Id (Email Address) must not have been found in either table.  Invalid Login -->
			<task synchronous="true" continue-on-failure="false" name="setInvalidLoginErrorMsg">
				<task-object-name>com.tsa.puridiom.vendorregistration.authentication.tasks.ErrorMsgSetInvalidLogin</task-object-name>
				<post-action>exitProcess</post-action>
			</task>
		</activity>
		<activity synchronous="true" continue-on-failure="false" name="resetPasswordLinkHelp">
			<task synchronous="true" continue-on-failure="false" name="resetPasswordLinkSetup">
				<task-object-name>com.tsa.puridiom.resetpassword.ResetPasswordLinkCreateSetup</task-object-name>
			</task>
			<task synchronous="true" continue-on-failure="false" name="resetPasswordLinkAdd">
				<task-object-name>com.tsa.puridiom.supplierportal.InvokeSupplierPortalProcessTask</task-object-name>
				<process-filename>resetpassword-add.xml</process-filename>
			</task>
			<task synchronous="true" continue-on-failure="false" name="sendResetPasswordLink">
				<task-object-name>com.tsa.puridiom.resetpassword.ResetPasswordLinkSendEmail</task-object-name>
			</task>
			<post-action>exitProcess</post-action>
		</activity>

		<!-- <activity synchronous="true" continue-on-failure="false" name="passwordHelp">
			<task synchronous="true" continue-on-failure="false" name="sendPassword">
				<task-object-name>com.tsa.puridiom.vendorregister.tasks.PasswordHelpSend</task-object-name>
			</task>
		</activity> -->

		<activity synchronous="true" continue-on-failure="false" name="setUserInCache">
			<task synchronous="true" continue-on-failure="false" name="setUserInCache">
				<task-object-name>com.tsa.puridiom.vendorregistration.authentication.tasks.SetRegisterUserInCache</task-object-name>
				<post-action></post-action>
			</task>
		</activity>
	</activities>
</process>